# Generated by Django 4.2.30 on 2026-07-21 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('previous_commit', models.CharField(blank=True, default='', max_length=64)),
                ('new_commit', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('updated', 'Updated'), ('no_change', 'No Change'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_history', to='dashboard.repository')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['checked_at'], name='dashboard_u_checked_5ba38f_idx'), models.Index(fields=['status'], name='dashboard_u_status_05994f_idx'), models.Index(fields=['repository', 'checked_at'], name='dashboard_u_reposit_e68680_idx')],
            },
        ),
    ]
