# Generated by Django 4.2.30 on 2026-07-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_updatehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines_of_code', models.IntegerField(blank=True, null=True)),
                ('file_count', models.IntegerField(blank=True, null=True)),
                ('repository_size_mb', models.FloatField(blank=True, null=True)),
                ('cyclomatic_complexity', models.FloatField(blank=True, null=True)),
                ('maintainability_index', models.FloatField(blank=True, null=True)),
                ('technical_debt_hours', models.FloatField(blank=True, null=True)),
                ('technical_debt_density', models.FloatField(blank=True, null=True)),
                ('analysed_at', models.DateTimeField(auto_now_add=True)),
                ('commit_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='dashboard.repository')),
            ],
            options={
                'db_table': 'analysis_run',
                'ordering': ['-analysed_at'],
            },
        ),
    ]
