# Generated by Django 4.2.30 on 2026-07-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_analysisrun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={},
        ),
        migrations.AlterModelTable(
            name='repository',
            table='repositories',
        ),
    ]
