# Generated by Django 4.2.30 on 2026-07-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_repository_options_alter_repository_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='updatehistory',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='updatehistory',
            name='dashboard_u_checked_5ba38f_idx',
        ),
        migrations.RemoveIndex(
            model_name='updatehistory',
            name='dashboard_u_status_05994f_idx',
        ),
        migrations.RemoveIndex(
            model_name='updatehistory',
            name='dashboard_u_reposit_e68680_idx',
        ),
        migrations.AlterModelTable(
            name='analysisrun',
            table='Analysis_Run',
        ),
        migrations.AlterModelTable(
            name='repository',
            table='Repositories',
        ),
        migrations.AlterModelTable(
            name='updatehistory',
            table='UpdateHistory',
        ),
    ]
