# Generated by Django 4.2.30 on 2026-07-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_updatehistory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrun',
            name='technical_debt_density',
        ),
        migrations.RemoveField(
            model_name='analysisrun',
            name='technical_debt_hours',
        ),
    ]
