# Generated by Django 4.2.30 on 2026-07-28 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_analysisrun_technical_debt_density_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('project_status', models.CharField(choices=[('active', 'Active'), ('watch', 'Watch'), ('drop_candidate', 'Drop Candidate'), ('dropped', 'Dropped'), ('archived', 'Archived')], default='active', max_length=30)),
                ('drop_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'project_status',
            },
        ),
        migrations.AlterModelOptions(
            name='updatehistory',
            options={'ordering': ['-checked_at']},
        ),
        migrations.AddIndex(
            model_name='updatehistory',
            index=models.Index(fields=['checked_at'], name='UpdateHisto_checked_e759ab_idx'),
        ),
        migrations.AddIndex(
            model_name='updatehistory',
            index=models.Index(fields=['status'], name='UpdateHisto_status_b92a91_idx'),
        ),
        migrations.AddIndex(
            model_name='updatehistory',
            index=models.Index(fields=['repository', 'checked_at'], name='UpdateHisto_reposit_b3e03a_idx'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='repository',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='dashboard.repository'),
        ),
    ]
