# Generated by Django 4.2.30 on 2026-08-04 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_projectstatus_alter_updatehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=40)),
                ('commit_date', models.DateField()),
                ('month', models.CharField(blank=True, max_length=7)),
                ('total_complexity', models.FloatField(default=0)),
                ('average_complexity', models.FloatField(default=0)),
                ('function_count', models.PositiveIntegerField(default=0)),
                ('nloc', models.PositiveIntegerField(default=0)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexity_snapshots', to='dashboard.repository')),
            ],
            options={
                'ordering': ['commit_date'],
                'indexes': [models.Index(fields=['repository', 'commit_date'], name='dashboard_c_reposit_7759d9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='complexitysnapshot',
            constraint=models.UniqueConstraint(fields=('repository', 'commit_hash'), name='unique_repository_complexity_commit'),
        ),
    ]
