# Generated by Django 4.2.30 on 2026-08-04 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_complexitysnapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexitysnapshot',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='complexitysnapshot',
            name='unique_repository_complexity_commit',
        ),
        migrations.RemoveIndex(
            model_name='complexitysnapshot',
            name='dashboard_c_reposit_7759d9_idx',
        ),
        migrations.AlterModelTable(
            name='complexitysnapshot',
            table='ComplexitySnapshot',
        ),
    ]
