# Generated by Django 4.2.30 on 2026-08-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_complexitysnapshot_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='project_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='repository',
            name='project_language',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
